#!/usr/bin/env bash
# Configures HAProxy to accept requests on port 80 and redirect to web servers

sudo apt update -y
sudo apt install haproxy -y

# Backup original config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create new config
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 6912-web-01 3.89.121.247:80 check
    server 6912-web-02 34.227.27.109:80 check
EOF

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
